---
abstract: 'Automate Perl distribution releases'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
keywords:
  - workflow
  - module
  - distribution
  - pause
  - automation
  - testing
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Release
no_index:
  directory:
    - t
    - inc
requires:
  CACertOrg::CA: 0
  ConfigReader::Simple: 0
  IO::Null: 0
  Mojo::UserAgent: 0
  Test::Output: 0
  Test::Without::Module: 0
  URI: 0
  perl: 5.01
resources:
  repository: git://github.com/briandfoy/module-release.git
version: 2.06_05
