# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Release
version:      1.10
version_from: lib/Release.pm
installdirs:  site
requires:
    ConfigReader::Simple:          0
    Crypt::SSLeay:                 0
    File::Temp:                    0
    HTTP::Message:                 0
    Net::FTP:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
