--- #YAML:1.0
name:               Module-Release
version:            2.05_06
abstract:           Automate Perl distribution releases
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CACertOrg::CA:        0
    ConfigReader::Simple:  0
    HTTP::Message:        0
    HTTP::Request:        0
    IO::Null:             0
    LWP::Protocol::https:  6.02
    LWP::UserAgent:       6.02
    Net::FTP:             0
    perl:                 5.008
    Test::Output:         0
    Test::Without::Module:  0
    URI:                  0
resources:
    repository:  git://github.com/briandfoy/module-release.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - workflow
    - module
    - distribution
    - pause
    - automation
    - testing
