--- #YAML:1.0
name:               Module-Release
version:            2.01
abstract:           Automate software releases
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    ConfigReader::Simple:  0
    Crypt::SSLeay:        0
    HTTP::Message:        0
    HTTP::Request:        0
    IO::Null:             0
    Net::FTP:             0
    Test::Output:         0
    URI:                  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
