--- #YAML:1.0
name:                Module-Release
version:             1.17_10
abstract:            Automate software releases
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    ConfigReader::Simple:          0
    Crypt::SSLeay:                 0
    File::Temp:                    0
    HTTP::Message:                 0
    IO::Null:                      0
    Net::FTP:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - brian d foy <bdfoy@cpan.org>
